Develop
AysuDemirci/Daily_Exchange_Rate_Tracking pull request #10
Opened 2022-12-06 21:34 UTC by AysuDemirci

2022-12-08 19:07 UTC, tylndemirci requested changes

2022-12-08 19:07 UTC, tylndemirci commented on src/App.js
> +  componentDidMount() {
useEffect

2022-12-08 19:07 UTC, tylndemirci commented on src/App.js
> +          x.price = Math.floor(Math.random() * 50);
math.floor düz sayılar verir, float türünde veri olması gerek

2022-12-08 19:40 UTC, AysuDemirci commented on src/App.js
> +  componentDidMount() {
class componentlerde componentdidmount useeffect yerine kullanılıyor. benimki ise class component.

2022-12-08 19:54 UTC, tylndemirci commented on src/App.js
> +  componentDidMount() {
referanslardan kaldıralım o zaman

2022-12-08 20:09 UTC, AysuDemirci commented on src/App.js
> +  componentDidMount() {
nasıl olacak?

2022-12-09 20:54 UTC, tylndemirci approved these changes

2022-12-09 20:56 UTC, merged